ASPFinalSolution/ASPFinal/Areas/Control/Controllers/BlogReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASPFinal.Areas.Control.Filters;
using ASPFinal.DAL;
using ASPFinal.Models;

namespace ASPFinal.Areas.Control.Controllers
{
    [Auth]
    public class BlogReviewsController : Controller
    {
        private JoobsyDbContext db = new JoobsyDbContext();

        // GET: Control/BlogReviews
        public ActionResult Index()
        {
            var blogReviews = db.BlogReviews.Include(b => b.Blog).Include(b => b.Candidate);
            return View(blogReviews.ToList());
        }

        // GET: Control/BlogReviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogReview blogReview = db.BlogReviews.Find(id);
            if (blogReview == null)
            {
                return HttpNotFound();
            }
            return View(blogReview);
        }

        [HttpPost]
        public JsonResult Edit(int? id,bool status)
        {
            if (id == null)
            {
                return Json(new { res = true }, JsonRequestBehavior.AllowGet);
            }
            BlogReview blogReview = db.BlogReviews.Find(id);
            if (blogReview == null)
            {
                return Json(new { res = true }, JsonRequestBehavior.AllowGet);
            }
            blogReview.Status = status;
            db.SaveChanges();
            return Json(new {res = true },JsonRequestBehavior.AllowGet);
        }

        // GET: Control/BlogReviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogReview blogReview = db.BlogReviews.Find(id);
            if (blogReview == null)
            {
                return HttpNotFound();
            }
            db.BlogReviews.Remove(blogReview);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASPFinalSolution/ASPFinal/Areas/Control/Views/BlogReviews/Details.cshtml
@model ASPFinal.Models.BlogReview

@{
    ViewBag.Title = "Blog Review Details";
    Layout = "~/Areas/Control/Views/Shared/_LayoutControl.cshtml";
}

    <h2>Blog Review Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Blog.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Blog.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Candidate.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Candidate.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index",null,new { @class="btn btn-dark"})
</p>

ASPFinalSolution/ASPFinal/Areas/Control/Views/BlogReviews/Index.cshtml
@model IEnumerable<ASPFinal.Models.BlogReview>

@{
    ViewBag.Title = "Blog Reviews";
    Layout = "~/Areas/Control/Views/Shared/_LayoutControl.cshtml";
}

<h2>Blog Reviews</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Candidate.Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Blog.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Candidate.Firstname @item.Candidate.Lastname
            </td>
            <td>
                @(item.Blog.Title.Length > 50 ? item.Blog.Title.Substring(0, 50) + " ..." : item.Blog.Title)
            </td>
            <td class="statusActive">
                @if (item.Status == true)
                {
                    <a href="@Url.Action("edit","blogReviews",new { id=item.Id, status=false})" class="statusActive">
                <span class="badge badge-success">Avtiv</span></a>
                }
                else
                {
                    <a href="@Url.Action("edit","blogReviews",new { id=item.Id,status=true})" class="statusActive">
                        <span class="badge badge-danger">Deactive</span>
                    </a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a href="@Url.Action("details","BlogReviews",new { id= item.Id})"><i class="fas fa-info-circle text-warning"></i></a> |
                <a class="jobDelete" href="@Url.Action("delete","BlogReviews",new { id= item.Id})"><i class="fas fa-trash text-danger"></i></a>
            </td>
        </tr>
    }

</table>